In [1]:
import numpy as np
np.random.seed(0)

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(5, 10, size=(7, 8))
x3 = np.random.randint(5, 25, size=(7, 8, 3))

x1, x2, x3

(array([5, 0, 3, 3, 7, 9]),
 array([[8, 7, 9, 5, 5, 9, 7, 6],
        [5, 6, 6, 5, 6, 9, 8, 5],
        [8, 5, 7, 8, 5, 6, 8, 8],
        [8, 5, 6, 6, 6, 5, 7, 9],
        [8, 8, 7, 9, 7, 5, 5, 9],
        [5, 9, 6, 9, 6, 7, 7, 5],
        [6, 6, 6, 6, 8, 8, 7, 8]]),
 array([[[ 5, 19,  8],
         [17, 15, 16],
         [ 9, 11,  9],
         [20,  8, 17],
         [ 9, 13, 19],
         [20,  8, 20],
         [18, 21, 22],
         [10, 14,  8]],
 
        [[ 5, 10,  5],
         [22, 23,  9],
         [ 7, 21,  8],
         [ 7, 15, 18],
         [21, 12, 14],
         [ 5, 15, 23],
         [16,  7,  7],
         [ 8,  8, 23]],
 
        [[19,  8, 22],
         [23, 19, 14],
         [ 6,  9, 15],
         [16, 13, 16],
         [ 7, 24, 21],
         [ 5,  5, 11],
         [24, 19, 15],
         [24, 13, 18]],
 
        [[ 7,  8,  7],
         [16, 18, 21],
         [13, 13, 24],
         [13,  7,  8],
         [17, 19,  5],
         [ 9,  8, 18],
         [16, 18, 18],
         [

In [2]:
x3.ndim

3

In [3]:
x3.shape

(7, 8, 3)

In [4]:
x3.size

168

In [5]:
x3.dtype

dtype('int32')

In [6]:
x3[:2, :3]

array([[[ 5, 19,  8],
        [17, 15, 16],
        [ 9, 11,  9]],

       [[ 5, 10,  5],
        [22, 23,  9],
        [ 7, 21,  8]]])

In [7]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([ x, y ])

array([1, 2, 3, 3, 2, 1])

In [10]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
x1, x2, x3

(array([1, 2, 3]), array([99, 99]), array([3, 2, 1]))

In [13]:
theta = np.linspace(0, np.pi, 64)
theta

array([0.        , 0.04986655, 0.0997331 , 0.14959965, 0.1994662 ,
       0.24933275, 0.2991993 , 0.34906585, 0.3989324 , 0.44879895,
       0.4986655 , 0.54853205, 0.5983986 , 0.64826515, 0.6981317 ,
       0.74799825, 0.7978648 , 0.84773135, 0.8975979 , 0.94746445,
       0.997331  , 1.04719755, 1.0970641 , 1.14693065, 1.1967972 ,
       1.24666375, 1.2965303 , 1.34639685, 1.3962634 , 1.44612995,
       1.4959965 , 1.54586305, 1.5957296 , 1.64559615, 1.6954627 ,
       1.74532925, 1.7951958 , 1.84506235, 1.8949289 , 1.94479545,
       1.994662  , 2.04452855, 2.0943951 , 2.14426165, 2.1941282 ,
       2.24399475, 2.2938613 , 2.34372785, 2.3935944 , 2.44346095,
       2.4933275 , 2.54319405, 2.5930606 , 2.64292715, 2.6927937 ,
       2.74266025, 2.7925268 , 2.84239335, 2.8922599 , 2.94212645,
       2.991993  , 3.04185955, 3.0917261 , 3.14159265])

In [16]:
x = np.array(np.arange(0, 5))
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [20]:
np.add.reduce(x)

10

In [18]:
x

array([0, 1, 2, 3, 4])

In [21]:
np.add.accumulate(x)

array([ 0,  1,  3,  6, 10], dtype=int32)

In [22]:
x = np.array(np.arange(1, 10))
np.multiply.accumulate(x)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

In [23]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [35]:
X = np.round(np.random.random((3, 3)) * 10)
X

array([[ 7.,  5.,  5.],
       [ 8.,  2.,  9.],
       [ 3., 10.,  5.]])

In [36]:
X.max(axis=0)

array([ 8., 10.,  9.])

In [37]:
X.max(axis=1)

array([ 7.,  9., 10.])